bundle_audit:
  stage: test
  script: |
    gem install bundler-audit
    bundle-audit update
    bundle-audit check


staging:
  stage: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --app=omaps-2-staging --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master

production:
  stage: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --app=omaps-2-prod --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - tags